export const viewAllTableData = [
    {
      niumId: "N-001",
      orderDate: "18.02.2025",
      agentId:"1234",
      customerPan: "AFJPW0198D",
      transactionType: "Card Load VKYC + ESign",
      purposeType: "BTQ",
      esignStatus: "Pending",
      esignStatusCompletionDate:"06-02-2025 18:47:37 IST",
      vkycStatus: "Success",
      vkycCompletionDate:"06-02-2025 18:47:37 IST",
      incidentStatus: "pending",
      incidentCompletionDate:"06-02-2025 18:47:37 IST",
    },
    {
      niumId: "N-002",
      orderDate: "10.02.2025",
      agentId:"5678",
      customerPan: "AHURE123R",
      transactionType: "Card Reload ESign",
      purposeType: "BT",
      esignStatus: "Success",
      esignStatusCompletionDate:"06-02-2025 18:47:37 IST",
      vkycStatus: "Success",
      vkycCompletionDate:"06-02-2025 18:47:37 IST",
      incidentStatus: "Success",
      incidentCompletionDate:"06-02-2025 18:47:37 IST",
    },
    {
      niumId: "N-003",
      orderDate: "05.01.2025",
      agentId:"9123",
      customerPan: "AJYOI8986E",
      transactionType: "Encashment ESign",
      purposeType: "-",
      esignStatus: "Re-Generate",
      esignStatusCompletionDate:"Expired",
      vkycStatus: "Pending",
      vkycCompletionDate:"Expired",
      incidentStatus: "Re-Generate",
      incidentCompletionDate:"Expired",
    },
    {
      niumId: "N-004",
      orderDate: "28.12.2024",
      agentId:"2578",
      customerPan: "BYUOW345T",
      transactionType: "Remittance VKYC + ESign",
      purposeType: "University Fee - Self Funded",
      esignStatus: "Pending",
      esignStatusCompletionDate:"Pending",
      vkycStatus: "Pending",
      vkycCompletionDate:"Success",
      incidentStatus: "Pending",
      incidentCompletionDate:"Pending",
    },
  ];
  